export const CREATE_GAME_REQUEST_STARTED = 'CREATE_GAME_REQUEST_STARTED'
export const CREATE_GAME_REQUEST_FINISHED = 'CREATE_GAME_REQUEST_FINISHED'
export const CREATE_GAME_REQUEST_ERROR = 'CREATE_GAME_REQUEST_ERROR'

export const GET_GAMES_REQUEST_STARTED = 'GET_GAMES_REQUEST_STARTED'
export const GET_GAMES_REQUEST_FINISHED = 'GET_GAMES_REQUEST_FINISHED'
export const GET_GAMES_REQUEST_ERROR = 'GET_GAMES_REQUEST_ERROR'

export const UPDATE_GAME_DATA = 'UPDATE_GAME_DATA'

export const CONNECT_GAME_STARTED = 'CONNECT_GAME_STARTED'
export const CONNECT_GAME_FINISHED = 'CONNECT_GAME_FINISHED'
export const DISCONNECT_GAME = 'DISCONNECT_GAME'
export const DISCONNECT_GAME_ERROR = 'DISCONNECT_GAME_ERROR'