# Generated by Django 3.0.5 on 2020-12-06 12:17

from django.db import migrations, models
import djongo.models.fields
import wzrd.game_sessions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='Sample Game')),
                ('description', models.TextField(blank=True, default='')),
                ('game_master', models.IntegerField(blank=True, default=-1)),
                ('last_object_id', models.IntegerField(blank=True, default=1)),
                ('game_objects', wzrd.game_sessions.models.GameObjectsField(blank=True, default=dict)),
                ('active_users', wzrd.game_sessions.models.GameObjectsField(blank=True, default=dict)),
                ('chat', djongo.models.fields.JSONField(blank=True, default=list)),
                ('invitation_code', models.TextField(blank=True, default='XXXXXX')),
                ('is_private', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
