# Generated by Django 3.0.5 on 2020-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Sample Game')),
                ('description', models.TextField(blank=True, default='')),
                ('game_master', models.IntegerField(blank=True, default=0)),
                ('invitation_code', models.TextField(default='XXXXXX')),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
