# Generated by Django 3.0.5 on 2020-11-22 14:06

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game_objects',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
