# Generated by Django 3.0.6 on 2020-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
