version: "3.3"
services:
  nginx:
    build:
      context: nginx
      dockerfile: nginx.Dockerfile
    container_name: umr_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./_/media:/app/media
    depends_on:
      - wzrd
    networks:
      - inner

  wzrd:
    build: wzrd
    container_name: umr_wzrd
    volumes:
      - ./wzrd/wzrd:/app/wzrd
      - ./_/media:/app/media
    environment:
      APP_HOST: 207.154.226.69
    depends_on:
      - mongo
      - redis
    networks:
      - inner

  mongo:
    container_name: umr_mongo
    image: mongo:latest
    restart: always
    networks:
     - inner
    volumes:
      - ./_/mongodb:/data/db

  redis:
    container_name: umr_redis
    image: redis:latest
    restart: always
    networks:
     - inner
    volumes:
      - ./_/redis:/data

networks:
 inner:
   name: inner