# Generated by Django 3.0.5 on 2020-12-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='map',
            field=models.TextField(blank=True, default='Global'),
        ),
    ]
