# Generated by Django 3.0.5 on 2021-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_hero_herosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='sprite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
