# Generated by Django 3.0.5 on 2021-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_additional_fields_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
