export const LOGIN_REQUEST_STARTED = 'LOGIN_REQUEST_STARTED'
export const LOGIN_REQUEST_FINISHED = 'LOGIN_REQUEST_FINISHED'
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR'

export const LOGOUT = 'LOGOUT'

export const SIGNUP_REQUEST_STARTED = 'SIGNUP_REQUEST_STARTED'
export const SIGNUP_REQUEST_FINISHED = 'SIGNUP_REQUEST_FINISHED'
export const SIGNUP_REQUEST_ERROR = 'SIGNUP_REQUEST_ERROR'

export const MYSELF_REQUEST_STARTED = 'MYSELF_REQUEST_STARTED'
export const MYSELF_REQUEST_FINISHED = 'MYSELF_REQUEST_FINISHED'
export const MYSELF_REQUEST_ERROR = 'MYSELF_REQUEST_ERROR'

export const QUICK_START_REQUEST_STARTED = 'QUICK_START_REQUEST_STARTED'
export const QUICK_START_REQUEST_FINISHED = 'QUICK_START_REQUEST_FINISHED'