export const GET_HEROES_REQUEST_STARTED = 'GET_HEROES_REQUEST_STARTED'
export const GET_HEROES_REQUEST_FINISHED = 'GET_HEROES_REQUEST_FINISHED'
export const GET_HEROES_REQUEST_ERROR = 'GET_HEROES_REQUEST_ERROR'

export const ADD_HERO_REQUEST_STARTED = 'UPDATE_HERO_REQUEST_STARTED'
export const ADD_HERO_REQUEST_FINISHED = 'UPDATE_HERO_REQUEST_FINISHED'
export const ADD_HERO_REQUEST_ERROR = 'UPDATE_HERO_REQUEST_ERROR'