# Generated by Django 3.0.5 on 2021-04-10 16:44

from django.db import migrations, models
import wzrd.media.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=256, null=True, upload_to=wzrd.media.utils.media_slug)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
