# Generated by Django 3.0.5 on 2021-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.TextField(default='Untitled', null=True),
        ),
    ]
