# Generated by Django 3.0.5 on 2021-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.TextField(default='Untitled', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
