export const CREATE_GAME_REQUEST_STARTED = 'CREATE_GAME_REQUEST_STARTED'
export const CREATE_GAME_REQUEST_FINISHED = 'CREATE_GAME_REQUEST_FINISHED'
export const CREATE_GAME_REQUEST_ERROR = 'CREATE_GAME_REQUEST_ERROR'

export const GET_GAME_HISTORY_REQUEST_STARTED = 'GET_GAME_HISTORY_REQUEST_STARTED'
export const GET_GAME_HISTORY_REQUEST_FINISHED = 'GET_GAME_HISTORY_REQUEST_FINISHED'
export const GET_GAME_HISTORY_REQUEST_ERROR = 'GET_GAME_HISTORY_REQUEST_ERROR'

export const GET_GM_GAME_HISTORY_REQUEST_STARTED = 'GET_GM_GAME_HISTORY_REQUEST_STARTED'
export const GET_GM_GAME_HISTORY_REQUEST_FINISHED = 'GET_GM_GAME_HISTORY_REQUEST_FINISHED'
export const GET_GM_GAME_HISTORY_REQUEST_ERROR = 'GET_GM_GAME_HISTORY_REQUEST_ERROR'

export const GET_PUBLIC_GAMES_REQUEST_STARTED = 'GET_PUBLIC_GAMES_REQUEST_STARTED'
export const GET_PUBLIC_GAMES_REQUEST_FINISHED = 'GET_PUBLIC_GAMES_REQUEST_FINISHED'
export const GET_PUBLIC_GAMES_REQUEST_ERROR = 'GET_PUBLIC_GAMES_REQUEST_ERROR'

export const UPDATE_GAME_DATA = 'UPDATE_GAME_DATA'

export const CONNECT_GAME_STARTED = 'CONNECT_GAME_STARTED'
export const CONNECT_GAME_FINISHED = 'CONNECT_GAME_FINISHED'
export const DISCONNECT_GAME = 'DISCONNECT_GAME'
export const CONNECT_GAME_ERROR = 'CONNECT_GAME_ERROR'

export const DELETE_GAME_REQUEST_FINISHED = 'DELETE_GAME_REQUEST_FINISHED'