import { getConstants } from '../../helpers/getConstants'

const gameConstants = getConstants([
    'CREATE_GAME_REQUEST_STARTED',
    'CREATE_GAME_REQUEST_FINISHED',
    'CREATE_GAME_REQUEST_ERROR',

    'GET_ALL_GAMES_REQUEST_STARTED',
    'GET_ALL_GAMES_REQUEST_FINISHED',
    'GET_ALL_GAMES_REQUEST_ERROR',

    'GET_GAME_HISTORY_REQUEST_STARTED',
    'GET_GAME_HISTORY_REQUEST_FINISHED',
    'GET_GAME_HISTORY_REQUEST_ERROR',

    'GET_GM_GAME_HISTORY_REQUEST_STARTED',
    'GET_GM_GAME_HISTORY_REQUEST_FINISHED',
    'GET_GM_GAME_HISTORY_REQUEST_ERROR',

    'GET_PUBLIC_GAMES_REQUEST_STARTED',
    'GET_PUBLIC_GAMES_REQUEST_FINISHED',
    'GET_PUBLIC_GAMES_REQUEST_ERROR',

    'UPDATE_GAME_DATA',

    'CONNECT_GAME_STARTED',
    'CONNECT_GAME_FINISHED',
    'CONNECT_GAME_ERROR',
    'DISCONNECT_GAME',

    'DELETE_GAME_REQUEST_FINISHED'
])

export default gameConstants
