# Generated by Django 3.0.5 on 2020-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_hero_herosession'),
        ('users', '0004_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heroes',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='games.Hero'),
        ),
    ]
