export const markersList = [
    'Bonfire',
    'Castle',
    'Tavern',
    'Tree',
]

export const heroes = [
    'Ant',
    'Cat Smart',
    'Girl Strong',
    'Plant',
    'Snake03',
    'Troll',
    'Boy Cunning', 'Cat Strong', 'Goblin', 'Plant02', 'Snake04', 'Troll02',
    'Boy Smart', 'Dragon', 'Knight', 'Skeleton', 'Snake05', 'Wizard',
    'Boy Strong', 'Girl Cunning', 'Mummy', 'Snake', 'Spider', 'Wolf',
    'Cat Cunning', 'Girl Smart', 'Musician', 'Snake02', 'Thief'
]


export const globalSymbols = [
    'Bones1',
    'Bones2',
    'Bones3',
    'Chest',
    'City',
    'Dot',
    'Dungeon1',
    'Dungeon2',
    'Dungeon3',
    'Finsh',
    'Fire',
    'Flag',
    'Grass1',
    'Grass2',
    'Grass3',
    'Grass4',
    'Grass5',
    'Grass6',
    'Hill1',
    'Hill2',
    'Hill3',
    'Lake1',
    'Lake2',
    'Lake3',
    'Mountain1',
    'Mountain2',
    'Mountain3',
    'Mountain4',
    'Mountain5',
    'Start',
    'Swamp1',
    'Swamp2',
    'Tower1',
    'Tower2',
    'Tree1',
    'Tree2',
    'Tree3',
    'Tree4'
]
